name: github-actions

services:
  runner:
    build: .
    image: github-actions-runner
    restart: unless-stopped
    privileged: true
    environment:
      GITHUB_URL: ${GITHUB_URL:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      DOCKER_HOST: tcp://0.0.0.0:2375
    volumes:
      - ./start.sh:/start.sh
      #- /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
