name: github-actions

services:
  runner:
    build: .
    image: github-actions-runner
    restart: unless-stopped
    environment:
      GITHUB_URL: ${GITHUB_URL:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    volumes:
      - ./start.sh:/start.sh
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
